import { StyleSheet, Platform } from 'react-native';
import { UiColors, UiRadius, UiShadow } from '@/constants/ui';

const cardBase = {
  borderRadius: UiRadius.lg,
  borderWidth: StyleSheet.hairlineWidth + 0.5,
  borderColor: UiColors.border,
  overflow: 'hidden' as const,
  backgroundColor: UiColors.surface,
  ...UiShadow.card,
  ...(Platform.OS === 'web'
    ? { backdropFilter: 'blur(12px)', WebkitBackdropFilter: 'blur(12px)' }
    : {}),
};

export const dashboardStyles = StyleSheet.create({
  container: {
    paddingBottom: 20,
  },
  sectionHeading: {
    fontSize: 18,
    fontWeight: '600',
    color: UiColors.text,
    marginBottom: 14,
    marginTop: 10,
    letterSpacing: -0.3,
  },
  gridContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 24,
  },
  gridCard: {
    width: '48%',
    ...cardBase,
  },
  gridCardInner: {
    padding: 16,
    position: 'relative',
    zIndex: 10,
  },
  iconHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 6,
  },
  gridTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: UiColors.text,
  },
  gridNumber: {
    fontSize: 24,
    fontWeight: '700',
    color: UiColors.accent,
    marginTop: 4,
    letterSpacing: -0.5,
  },
  gridDesc: {
    fontSize: 12,
    color: UiColors.textSecondary,
    fontWeight: '500',
    marginTop: 4,
    lineHeight: 18,
  },
  infoCard: {
    ...cardBase,
    marginBottom: 24,
  },
  cardPadding: {
    padding: 20,
    position: 'relative',
    zIndex: 10,
  },
  infoTitle: {
    color: UiColors.text,
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 6,
  },
  infoDesc: {
    color: UiColors.textSecondary,
    fontSize: 14,
    lineHeight: 20,
  },
  actionsRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 16,
  },
  btnPrimary: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: UiColors.accent,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: UiRadius.md,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  btnSecondary: {
    flex: 1,
    backgroundColor: UiColors.surface,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: UiRadius.md,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: StyleSheet.hairlineWidth + 0.5,
    borderColor: UiColors.border,
  },
  btnText: {
    color: '#FFFFFF',
    fontWeight: '600',
    fontSize: 13,
  },
  btnTextSecondary: {
    color: UiColors.text,
    fontWeight: '600',
    fontSize: 13,
  },
  searchContainer: {
    borderRadius: UiRadius.md,
    overflow: 'hidden',
    borderWidth: StyleSheet.hairlineWidth + 0.5,
    borderColor: UiColors.border,
    marginBottom: 20,
    backgroundColor: UiColors.surfaceMuted,
    ...UiShadow.card,
  },
  searchInner: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    gap: 10,
  },
  searchInput: {
    flex: 1,
    color: UiColors.text,
    fontSize: 14,
  },
  memberRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: UiColors.borderLight,
  },
  avatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: UiColors.accentLight,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  avatarText: {
    color: UiColors.accent,
    fontWeight: '700',
  },
  memberInfo: {
    flex: 1,
  },
  memberName: {
    color: UiColors.text,
    fontWeight: '600',
    fontSize: 14,
  },
  memberDesc: {
    color: UiColors.textSecondary,
    fontSize: 12,
    marginTop: 2,
  },
  filterRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 16,
  },
  filterChipActive: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: UiRadius.md,
    backgroundColor: UiColors.accentLight,
    borderWidth: StyleSheet.hairlineWidth + 0.5,
    borderColor: 'rgba(61, 153, 26, 0.2)',
  },
  filterTextActive: {
    color: UiColors.accent,
    fontWeight: '600',
    fontSize: 13,
  },
  filterChip: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: UiRadius.md,
    backgroundColor: UiColors.surface,
    borderWidth: StyleSheet.hairlineWidth + 0.5,
    borderColor: UiColors.border,
  },
  filterText: {
    color: UiColors.textSecondary,
    fontWeight: '500',
    fontSize: 13,
  },
  eventItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: UiColors.borderLight,
  },
  dateBox: {
    width: 50,
    height: 50,
    borderRadius: UiRadius.sm,
    backgroundColor: UiColors.accentLight,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  dateMonth: {
    color: UiColors.accent,
    fontSize: 10,
    fontWeight: '700',
  },
  dateDay: {
    color: UiColors.accent,
    fontSize: 18,
    fontWeight: '800',
  },
  eventInfo: {
    flex: 1,
  },
  eventTitle: {
    color: UiColors.text,
    fontWeight: '600',
    fontSize: 15,
  },
  eventDesc: {
    color: UiColors.textSecondary,
    fontSize: 12,
    marginTop: 4,
  },
  btn: {
    backgroundColor: UiColors.accent,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: UiRadius.md,
    alignItems: 'center',
    marginTop: 12,
  },
  btnRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  btnRowText: {
    color: UiColors.accent,
    fontSize: 13,
    fontWeight: '600',
  },
  progressBarBg: {
    height: 6,
    backgroundColor: UiColors.borderLight,
    borderRadius: 3,
    marginBottom: 16,
    overflow: 'hidden',
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: UiColors.accent,
    borderRadius: 3,
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  trackTitle: {
    color: UiColors.text,
    fontSize: 15,
    fontWeight: '600',
  },
  trackStats: {
    color: UiColors.textSecondary,
    fontSize: 13,
    fontWeight: '500',
  },
  campTitle: {
    color: UiColors.text,
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 6,
  },
  campDesc: {
    color: UiColors.textSecondary,
    fontSize: 13,
    marginBottom: 4,
  },
  btnGroup: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 16,
  },
  actionBtn: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: UiRadius.sm,
    borderWidth: StyleSheet.hairlineWidth + 0.5,
    borderColor: UiColors.border,
    alignItems: 'center',
    backgroundColor: UiColors.surfaceMuted,
  },
  actionBtnText: {
    color: UiColors.text,
    fontSize: 12,
    fontWeight: '600',
  },
  exportBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: UiColors.accentLight,
    paddingVertical: 8,
    borderRadius: UiRadius.sm,
  },
  exportBtnText: {
    color: UiColors.accent,
    fontSize: 11,
    fontWeight: '600',
  },
  iconBox: {
    marginBottom: 12,
    padding: 12,
    backgroundColor: UiColors.accentLight,
    borderRadius: UiRadius.lg,
  },
  helpRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: UiColors.borderLight,
  },
  iconWrap: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: UiColors.surfaceMuted,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  helpTitle: {
    flex: 1,
    color: UiColors.text,
    fontSize: 15,
    fontWeight: '500',
  },
  supportCard: {
    padding: 20,
    borderRadius: UiRadius.lg,
    backgroundColor: UiColors.surface,
    borderWidth: StyleSheet.hairlineWidth + 0.5,
    borderColor: UiColors.border,
    ...UiShadow.card,
  },
  supportTitle: {
    color: UiColors.text,
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 6,
  },
  supportDesc: {
    color: UiColors.textSecondary,
    fontSize: 13,
    marginBottom: 16,
    lineHeight: 20,
  },
  supportBtn: {
    backgroundColor: UiColors.accent,
    paddingVertical: 12,
    borderRadius: UiRadius.sm,
    alignItems: 'center',
  },
  supportBtnText: {
    color: '#FFFFFF',
    fontWeight: '600',
    fontSize: 14,
  },
});
